name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Lint with pylint
      run: |
        pip install pylint
        # Search for actual errors
        pylint src/*/*.py -E
        # For warnings instead return always zero
        pylint src/*/*.py --exit-zero
    - name: Test with pytest
      run: |
        pip install pytest
        pip install tensorflow # Keras does not install any backend by default?
        pytest
